name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore -v n
    - name: Build
      run: dotnet build --configuration Release --no-restore -v n
    - name: Test
      run: dotnet test --no-restore -v n
    - name: Run benchmarks
      run: dotnet run -c release --project benchmarks/Lagoon.Benchmarks/Lagoon.Benchmarks.csproj
