name: Publish

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name : Pack
      run: dotnet pack --version-suffix "`date -u +%Y%m%d%H%M%S`" -o .
